version: "3"

services:

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - mailhog
    environment:
      - DEBUG=true
      - API_VERSION=0.1.0
      - DATABASE_PROTOCOL=postgresql+asyncpg
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=username
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=allocation
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
    volumes:
      - allocation:/src/allocation
      - tests:/tests
    entrypoint:
      - uvicorn
      - allocation.entrypoint.fastapi_:app --reload
      - --host=0.0.0.0
      - --port=80
    ports:
      - "80:80"
