version: "3.8"

services:

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    ports:
      - "5432:5432"
    env_file:
      - envs/local/postgres.env

  pgadmin:
    extends:
      file: docker-compose.yml
      service: pgadmin
    ports:
      - "8080:80"
    env_file:
      - envs/dev/pgadmin.env

  allocation:
    extends:
      file: docker-compose.yml
      service: allocation
    volumes:
      - ../allocation:/src/allocation
      - ../tests:/src/tests
    ports:
      - "8000:8000"
    command: >
      sh -c "
        python -m allocation.entrypoint.pre_start.wait_database &&
        python -m allocation.entrypoint.pre_start.create_table &&
        uvicorn allocation.entrypoint.fastapi_:app --reload --host=0.0.0.0 --port=8000
      "
    env_file:
      - envs/local/allocation.env

  mailhog:
    extends:
      file: docker-compose.yml
      service: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
